In [9]:
# Below works for centering the column heading

import pandas as pd
import numpy as np

def style_negative(v, props=''):
    return props if v < 0 else None

np.random.seed(0)
df = pd.DataFrame(np.random.randn(10,4), columns=['A','B','C','D'])


s = df.style.set_table_styles ([{'selector': 'th.col_heading', 
                         'props': 'text-align: center'}])


display(s)

In [2]:
import pandas as pd
import numpy as np
data =  pd.DataFrame(np.random.randn(5, 3), columns=list('ABC'))

# dictionary of column colors
coldict = {'A':'grey', 'C':'yellow'}

def highlight_cols(s, coldict):
    if s.name in coldict.keys():
        return ['background-color: {}'.format(coldict[s.name])] * len(s)
    return [''] * len(s)

data.style.apply(highlight_cols, coldict=coldict)